name: Output Issues Workflow

on: [issues, workflow_dispatch]

jobs: 
  output-issue-job: 

    runs-on: ubuntu-latest

    steps: 
      - name: Echo Issue Step
        run:  "${{ toJSON(github.event)}}"