# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Test & Deploy .NET Workflow

on: [push, workflow_dispatch]
# on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

# defaults: 
#   run: 
#     working-directory: ./SimpleTestProject


jobs:

  initial-output-job: 
    runs-on: ubuntu-latest

    outputs: 
      my-output-value: ${{ steps.publishOutput.outputs.myValue}}
    steps: 
      - name: Publish output 
        id: publishOutput
        run: myValue=HelloWorld >> $GITHUB_OUTPUT



  test-job:
    runs-on: ubuntu-latest

    defaults: 
      run: 
        working-directory: ./SimpleTestProject

    steps:
    - name: Download sourcecode from repository step
      uses: actions/checkout@v4

    - name: Setup .NET step
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies step
      run: dotnet restore

    - name: Build project step
      run: dotnet build --no-restore

    - name: Test project step
      run: dotnet test --no-build --verbosity normal


  build-publish-job: 
    runs-on: ubuntu-latest #Every job gets their own runner because its on a completely isolated VM! 

    needs: test-job #forces this job to run sequentially, AFTER the test-job job 

    defaults: 
      run: 
        working-directory: ./SimpleTestProject

    steps:
    - name: Download sourcecode from repository step
      uses: actions/checkout@v4

    - name: Setup .NET step
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies step
      run: dotnet restore

    - name: Build project step
      run: dotnet build --no-restore

    - name: Publish project step 
      run: dotnet publish -c Release

    - name: Update job artefact Step 
      uses: actions/upload-artifact@v4 #FYI Uses statements DO NOT respect the working-directory, and always runs relative to the repo root!
      with: 
        name: publish-files 
        path: SimpleTestProject/SimpleTestProject/bin/Release/net8.0/publish #Path to the folder that we want to make available as an artefact


  deploy-job: 
    runs-on: ubuntu-latest #Every job gets their own runner because its on a completely isolated VM! 

    needs: [build-publish-job, initial-output-job] #forces this job to run sequentially, AFTER the build-publish-job job 

    steps:
    - name: Get the build/publish artifacts
      uses: actions/download-artifact@v4
      with: 
        name: publish-files 

    #Note that the working directory would show the **contents** of the publish-files folder, rather than the folder itself. 
    - name: Output the current working directory 
      run: ls

    - name: Deploy project step
      run: echo "Deploying to x cloud environment..."


    - name: Print the output from previous job 
      run: echo "${{ needs.initial-output-job.outputs.my-output-value }}"